# Generated by Django 3.1.2 on 2020-10-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USERS'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
    ]
