# Generated by Django 3.1.2 on 2020-10-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0002_auto_20201009_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilizador',
        ),
        migrations.AlterModelOptions(
            name='utilizador',
            options={'verbose_name': 'UTILIZADOR', 'verbose_name_plural': 'UTILIZADORES'},
        ),
        migrations.AlterModelTable(
            name='utilizador',
            table='UTILIZADOR',
        ),
    ]
